services:

  db:
    container_name: main_db
    image: mysql
    restart: always
    environment: 
      - MYSQL_DATABASE=alta_deploy_test
      - MYSQL_ROOT_PASSWORD=toor
    healthcheck:
      test: ["CMD", "mysql", "-u", "root",  "-ptoor", "-e", "show databases"]
      interval: 10s
    ports:
      - 3306:3306

  app:
    container_name: go-app
    build: .
    restart: always
    ports:
      - 8080
    depends_on:
      db:
        condition: service_healthy

        