services:

  db:
    image: mysql
    restart: always
    environment: 
      - MYSQL_USER=root
      - MYSQL_DATABASE=alta_deploy_test
      - MYSQL_ROOT_PASSWORD=toor
    volumes:
      - database_mysql:/var/lib/mysql
    ports:
      - 3306:3306

  # app:
  #   build: .
  #   restart: always
  #   environment:
  #     storage: db
  #   ports:
  #     8080:8080
    # depends_on:
    #   appDb:
    #     condition: 